version: '3'
services:
  app:
    build:
      context: ./php
    volumes:
      - './../:/var/www/html'
      - './docker/sites:/etc/apache2/sites-available'
      - './docker/data/dev:/home/dev'
    links:
      - db
    depends_on:
      - db
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    networks:
      app_net:
        ipv4_address: 172.16.1.04
  db:
    image: 'mysql:5.7'
    volumes:
      - './base:/var/lib/mysql'
      - './sql:/home/sql'
    environment:
      MYSQL_DATABASE: upost
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306
    networks:
      app_net:
        ipv4_address: 172.16.1.03
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
